window.pdfStoriesA1 = window.pdfStoriesA1 || [];

window.pdfStoriesA1.push(
    {
        id: "story_a1_1",
        title: "أَحْمَدُ الطَّالِبُ الجَدِيدُ",
        text: "هَذَا هُوَ أَحْمَدُ. أَحْمَدُ طَالِبٌ جَدِيدٌ فِي الْمَدْرَسَةِ الإِبْتِدَائِيَّةِ. يَسْكُنُ أَحْمَدُ فِي بَيْتٍ كَبِيرٍ مَعَ أَسْرَتِهِ فِي مَدِينَةٍ جَمِيلَةٍ فِي الصَّبَاحِ الْبَاكِرِ ، يَسْتَيْقِظُ أَحْمَدُ مِنْ النَّوْمِ بِشَاطٍ، ثُمَّ يَغْسِلُ وَجْهَهُ وَيَدَيْهِ بِالْمَاءِ وَالصَّابُونِ. بَعْدَ ذَلِكَ، يَأْكُلُ الفطور اللَّذِيذَ مَعَ أَبِيهِ وَأُمِّهِ. يَشْرَبُ أَحْمَدُ الحَلِيبَ الدَّافِي وَيَأْكُلُ الخُبْزَ مَعَ الْجُبْنِ. يَحْمِلُ حَقِيبَتَهُ الْمَدْرَسِيَّةَ وَيَذْهَبُ إِلَى المَدْرَسَةِ مَشْيًا عَلَى الأَقْدَامِ. هُوَ يُحِبُّ المَعَلِّمِينَ وَالْأَصْدِقَاءَ كَثِيرًا",
        tr: "Bu Ahmet'tir. Ahmet ilkokulda yeni bir öğrencidir. Ahmet, güzel bir şehirde ailesiyle birlikte büyük bir evde yaşamaktadır. Sabahın erken saatlerinde Ahmet neşeyle uyanır, ardından yüzünü ve ellerini su ve sabunla yıkar. Bundan sonra babası ve annesiyle lezzetli bir kahvaltı yapar. Ahmet ılık süt içer ve peynirli ekmek yer. Okul çantasını taşır ve okula yürüyerek gider. Öğretmenlerini ve arkadaşlarını çok sever.",
        dict: { "هَذَا": "bu", "هُوَ": "odur", "أَحْمَدُ": "Ahmet", "طَالِبٌ": "öğrenci", "جَدِيدٌ": "yeni", "فِي": "de/da", "الْمَدْرَسَةِ": "okulda", "الإِبْتِدَائِيَّةِ": "ilkokul", "يَسْكُنُ": "yaşar", "بَيْتٍ": "evde", "كَبِيرٍ": "büyük", "مَعَ": "ile", "أَسْرَتِهِ": "ailesi", "مَدِينَةٍ": "şehirde", "جَمِيلَةٍ": "güzel", "الصَّبَاحِ": "sabah", "الْبَاكِرِ": "erken", "يَسْتَيْقِظُ": "uyanır", "مِنْ": "den/dan", "النَّوْمِ": "uykudan", "بِشَاطٍ": "neşeyle", "ثُمَّ": "sonra", "يَغْسِلُ": "yıkar", "وَجْهَهُ": "yüzünü", "وَيَدَيْهِ": "ve ellerini", "بِالْمَاءِ": "su ile", "وَالصَّابُونِ": "ve sabunla", "بَعْدَ": "sonra", "ذَلِكَ": "bundan", "يَأْكُلُ": "yer", "الفطور": "kahvaltı", "اللَّذِيذَ": "lezzetli", "أَبِيهِ": "babası", "وَأُمِّهِ": "ve annesi", "يَشْرَبُ": "içer", "الحَلِيبَ": "süt", "الدَّافِي": "ılık", "الخُبْزَ": "ekmek", "الْجُبْنِ": "peynir", "يَحْمِلُ": "taşır", "حَقِيبَتَهُ": "çantasını", "الْمَدْرَسِيَّةَ": "okul", "وَيَذْهَبُ": "ve gider", "إِلَى": "e/a", "مَشْيًا": "yürüyerek", "عَلَى": "üzerinde", "الأَقْدَامِ": "ayaklar", "يُحِبُّ": "sever", "المَعَلِّمِينَ": "öğretmenleri", "وَالْأَصْدِقَاءَ": "ve arkadaşları", "كَثِيرًا": "çok" },
        quiz: { question: "كَيْفَ يَذْهَبُ أَحْمَدُ إِلَى المَدْرَسَةِ؟ (Ahmet okula nasıl gider?)", options: ["مَشْيًا عَلَى الأَقْدَامِ (Yürüyerek)", "بِالحَافِلَةِ (Otobüsle)", "بِالسَّيَّارَةِ (Arabayla)", "بِالدَّرَّاجَةِ (Bisikletle)"], correctIndex: 0 }
    },
    {
        id: "story_a1_2",
        title: "فَاطِمَةُ فِي السُّوقِ وَالحَدِيقَةِ",
        text: "تَسْكُنُ فَاطِمَةُ فِي قَرْيَةٍ صَغِيرَةٍ وَهَادِئَةٍ فِي يَوْمِ العُطْلَةِ، تَذْهَبُ فَاطِمَةُ إِلَى السُّوقِ الكَبِيرِ مَعَ أُمَّهَا لِشِرَاءِ الخَضْرَاوَاتِ وَالفَوَاكِةُ المُنَعِشَةِ. تَشْتَرِي الْأُمُّ الطَّمَاطِمَ وَالخِيَارَ وَالْجَزَرَ، وَتَشْتَرِي فَاطِمَةُ التَّفَّاحَ الْأَحْمَرَ وَالْمَوْزَ الأَصْفَرَ . بَعْدَ التَّسَوُّقِ، تَذْهَبَانِ إِلَى حَدِيقَةِ المَدِينَةِ. تَجْلِسُ فَاطِمَةُ عَلَى الكُرْسِيِّ الخَشَبِي وَتَأْكُلُ تُفَّاحَةً لَذِيذَةً. تَنْظُرُ فَاطِمَةُ إِلَى الْأَزْهَارِ المُلَوَّنَةِ وَالطُّيُورِ الجَمِيلَةِ فِي السَّمَاءِ وَتَشْعُرُ بِالسَّعَادَةِ الكَبِيرَة",
        tr: "Fatma küçük ve sakin bir köyde yaşamaktadır. Tatil gününde Fatma, taze sebze ve meyveler satın almak için annesiyle birlikte büyük pazara gider. Anne domates, salatalık ve havuç alır; Fatma ise kırmızı elma ve sarı muz alır. Alışverişten sonra şehir parkına giderler. Fatma ahşap bankta oturur ve lezzetli bir elma yer. Fatma renklere bürünmüş çiçeklere ve gökyüzündeki güzel kuşlara bakarak büyük bir mutluluk hisseder.",
        dict: { "تَسْكُنُ": "yaşar", "فَاطِمَةُ": "Fatma", "فِي": "de/da", "قَرْيَةٍ": "köyde", "صَغِيرَةٍ": "küçük", "وَهَادِئَةٍ": "ve sakin", "يَوْمِ": "günü", "العُطْلَةِ": "tatil", "تَذْهَبُ": "gider", "إِلَى": "e/a", "السُّوقِ": "pazara", "الكَبِيرِ": "büyük", "مَعَ": "ile", "أُمَّهَا": "annesi", "لِشِرَاءِ": "satın almak için", "الخَضْرَاوَاتِ": "sebzeler", "وَالفَوَاكِةُ": "ve meyveler", "المُنَعِشَةِ": "taze", "تَشْتَرِي": "satın alır", "الْأُمُّ": "anne", "الطَّمَاطِمَ": "domates", "وَالخِيَارَ": "ve salatalık", "وَالْجَزَرَ": "ve havuç", "التَّفَّاحَ": "elma", "الْأَحْمَرَ": "kırmızı", "وَالْمَوْزَ": "ve muz", "الأَصْفَرَ": "sarı", "بَعْدَ": "sonra", "التَّسَوُّقِ": "alışverişten", "تَذْهَبَانِ": "ikisi gider", "حَدِيقَةِ": "parkına", "المَدِينَةِ": "şehrin", "تَجْلِسُ": "oturur", "عَلَى": "üzerinde", "الكُرْسِيِّ": "bank", "الخَشَبِي": "ahşap", "وَتَأْكُلُ": "ve yer", "تُفَّاحَةً": "bir elma", "لَذِيذَةً": "lezzetli", "تَنْظُرُ": "bakar", "الْأَزْهَارِ": "çiçeklere", "المُلَوَّنَةِ": "renkli", "وَالطُّيُورِ": "ve kuşlara", "الجَمِيلَةِ": "güzel", "السَّمَاءِ": "gökyüzünde", "وَتَشْعُرُ": "ve hisseder", "بِالسَّعَادَةِ": "mutluluk", "الكَبِيرَة": "büyük" },
        quiz: { question: "مَاذَا تَشْتَرِي فَاطِمَةُ مِنَ السُّوقِ؟ (Fatma pazardan ne satın alır?)", options: ["التَّفَّاحَ الْأَحْمَرَ وَالْمَوْزَ الأَصْفَرَ (Kırmızı elma ve sarı muz)", "الطَّمَاطِمَ وَالخِيَارَ (Domates ve salatalık)", "الخُبْزَ وَالْجُبْنِ (Ekmek ve peynir)", "الحَلِيبَ (Süt)"], correctIndex: 0 }
    },
    {
        id: "story_a1_3",
        title: "قِطُّ عُمَرَ الصَّغِيرُ",
        text: "فِي بَيْتِ عُمَرَ قِطٌ صَغِيرٌ وَجَمِيلٌ اسْمُهُ مِشْمِش . لَوْنُ القِطَّ أَبْيَضُ وَعَيْنَاهُ زَرْقَاوَانِ. فِي الصَّبَاحِ، يَلْعَبُ مِشْمِش بالكُرَةِ الصَّغِيرَةِ فِي غُرْفَةِ المَعِيشَةِ. بَعْدَ اللَّعِبِ، يَشْرَبُ القِطُّ الحَلِيبَ البَارِدَ فِي الطَّبَقِ الصَّغِيرِ عِنْدَمَا يَشْعُرُ مِشْمِش بِالتَّعَبِ، يَذْهَبُ إِلَى السَّرِيرِ وَيَنَامُ بِهُدُوءٍ تَحْتَ الشَّمْسِ عُمَرُ يُحِبُّ قِطَّهُ كَثِيرًا وَيَلْعَبُ مَعَهُ كُلَّ يَوْمٍ بَعْدَ الْعَوْدَةِ مِنَ المَدْرَسَةِ. هُمَا صَدِيقَانِ مُقَرَّبَانِ جِدًّا",
        tr: "Ömer'in evinde Mişmiş adında küçük ve güzel bir kedi vardır. Kedinin rengi beyaz, gözleri ise mavidir. Sabahları Mişmiş oturma odasında küçük bir topla oynar. Oyun oynadıktan sonra kedi küçük tabaktaki soğuk sütü içer. Mişmiş yorulduğunda yatağa gider ve güneşin altında sessizce uyur. Ömer kedisini çok sever ve okuldan döndükten sonra her gün onunla oynar. Onlar çok yakın iki arkadaştır.",
        dict: { "فِي": "de/da", "بَيْتِ": "evinde", "عُمَرَ": "Ömer'in", "قِطٌ": "kedi", "صَغِيرٌ": "küçük", "وَجَمِيلٌ": "ve güzel", "اسْمُهُ": "adı", "مِشْمِش": "Mişmiş", "لَوْنُ": "rengi", "القِطَّ": "kedinin", "أَبْيَضُ": "beyaz", "وَعَيْنَاهُ": "ve gözleri", "زَرْقَاوَانِ": "mavi", "الصَّبَاحِ": "sabah", "يَلْعَبُ": "oynar", "بالكُرَةِ": "topla", "الصَّغِيرَةِ": "küçük", "غُرْفَةِ": "odasında", "المَعِيشَةِ": "oturma", "بَعْدَ": "sonra", "اللَّعِبِ": "oyundan", "يَشْرَبُ": "içer", "الحَلِيبَ": "süt", "البَارِدَ": "soğuk", "الطَّبَقِ": "tabakta", "عِنْدَمَا": "olduğunda", "يَشْعُرُ": "hisseder", "بِالتَّعَبِ": "yorgunluk", "يَذْهَبُ": "gider", "السَّرِيرِ": "yatağa", "وَيَنَامُ": "ve uyur", "بِهُدُوءٍ": "sessizce", "تَحْتَ": "altında", "الشَّمْسِ": "güneşin", "يُحِبُّ": "sever", "قِطَّهُ": "kedisini", "كَثِيرًا": "çok", "وَيَلْعَبُ": "ve oynar", "مَعَهُ": "onunla", "كُلَّ": "her", "يَوْمٍ": "gün", "الْعَوْدَةِ": "dönüşten", "مِنَ": "den/dan", "المَدْرَسَةِ": "okuldan", "هُمَا": "ikisi", "صَدِيقَانِ": "iki arkadaş", "مُقَرَّبَانِ": "yakın", "جِدًّا": "çok" },
        quiz: { question: "مَا هُوَ لَوْنُ القِطِّ مِشْمِش؟ (Mişmiş adlı kedinin rengi nedir?)", options: ["أَبْيَضُ (Beyaz)", "أَسْوَدُ (Siyah)", "أَصْفَرُ (Sarı)", "بُنِّيٌّ (Kahverengi)"], correctIndex: 0 }
    },
    {
        id: "story_a1_4",
        title: "خَالِدٌ فِي الحَدِيقَةِ الْعَامَّةِ",
        text: "اليَوْمَ الطَّقْسُ جَمِيلٌ جدا ، الشَّمْسُ مُشْرِقَةٌ وَالسَّمَاءُ صَافِيَةٌ. يَذْهَبُ خَالِدٌ مَعَ أَصْدِقَائِهِ إِلَى الْحَدِيقَةِ الْعَامَّةِ فِي المَسَاءِ. يَلْعَبُ الأَوْلَادُ كُرَةَ القَدَمِ عَلَى العُشْبِ الأَخْضَرِ بِفَرَح كَبِيرٍ. بَعْدَ المَبَارَاةِ، يَجْلِسُ خَالِدٌ تَحْتَ شَجَرَةٍ كَبِيرَةٍ وَيَشْرَبُ المَاءَ البَارِدَ لأَنَّهُ يَشْعُرُ بِالْعَطَشِ. ثُمَّ يَأْكُلُ المِثْلَجَاتِ بِلَذَّةٍ. يَعُودُ خَالِدٌ إِلَى البَيْتِ فِي الْمَسَاءِ وَهُوَ مَسْرُورٌ جِدًّا بِهَذَا الْيَوْمِ الرَّائِعِ مَعَ أَصْحَابِهِ",
        tr: "Bugün hava çok güzel, güneş parlıyor ve gökyüzü açık. Halit akşam arkadaşlarıyla birlikte halk parkına gidiyor. Çocuklar yeşil çimlerin üzerinde büyük bir neşeyle futbol oynuyorlar. Maçtan sonra Halit büyük bir ağacın altına oturuyor ve susadığı için soğuk su içiyor. Sonra tadını çıkararak dondurma yiyor. Halit arkadaşlarıyla geçirdiği bu harika günden dolayı çok mutlu bir şekilde akşam eve dönüyor.",
        dict: { "اليَوْمَ": "bugün", "الطَّقْسُ": "hava", "جَمِيلٌ": "güzel", "جدا": "çok", "الشَّمْسُ": "güneş", "مُشْرِقَةٌ": "parlıyor", "وَالسَّمَاءُ": "ve gökyüzü", "صَافِيَةٌ": "açık", "يَذْهَبُ": "gidiyor", "خَالِدٌ": "Halit", "مَعَ": "ile", "أَصْدِقَائِهِ": "arkadaşları", "إِلَى": "e/a", "الْحَدِيقَةِ": "parka", "الْعَامَّةِ": "halk", "فِي": "de/da", "المَسَاءِ": "akşam", "يَلْعَبُ": "oynuyor", "الأَوْلَادُ": "çocuklar", "كُرَةَ": "topu", "القَدَمِ": "ayak", "عَلَى": "üzerinde", "العُشْبِ": "çimlerin", "الأَخْضَرِ": "yeşil", "بِفَرَح": "neşeyle", "كَبِيرٍ": "büyük", "بَعْدَ": "sonra", "المَبَارَاةِ": "maçtan", "يَجْلِسُ": "oturuyor", "تَحْتَ": "altına", "شَجَرَةٍ": "ağacın", "وَيَشْرَبُ": "ve içiyor", "المَاءَ": "suyu", "البَارِدَ": "soğuk", "لأَنَّهُ": "çünkü o", "يَشْعُرُ": "hissediyor", "بِالْعَطَشِ": "susuzluk", "ثُمَّ": "sonra", "يَأْكُلُ": "yiyor", "المِثْلَجَاتِ": "dondurma", "بِلَذَّةٍ": "keyifle", "يَعُودُ": "dönüyor", "البَيْتِ": "eve", "مَسْرُورٌ": "mutlu", "الرَّائِعِ": "harika", "أَصْحَابِهِ": "arkadaşlarıyla" },
        quiz: { question: "مَاذَا يَأْكُلُ خَالِدٌ بَعْدَ المَبَارَاةِ؟ (Halit maçtan sonra ne yer?)", options: ["المِثْلَجَاتِ (Dondurma)", "التَّفَّاحَ (Elma)", "الخُبْزَ (Ekmek)", "الشُّورَبَةَ (Çorba)"], correctIndex: 0 }
    },
    {
        id: "story_a1_5",
        title: "زَيْنَبُ فِي المَكْتَبَةِ المَرْكَزِيَّةِ",
        text: "هَذِهِ هِيَ المَكْتَبَةُ المَرْكَزِيَّةُ الكَبِيرَةُ فِي المَدِينَةِ. تَذْهَبُ زَيْنَبُ إِلَى المَكْتَبَةِ كُلَّ يَوْمِ سَبْتٍ لِقِرَاءَةِ الكُتُبِ الْمُفِيدَةِ. المَكْتَبَةُ هَادِئَةٌ جِدًا وَفِيهَا كُتُبٌ كَثِيرَةٌ وَمُتَنَوّعَةٌ. تَخْتَارُ زَيْنَبُ كِتَابًا صَغِيرًا عَنِ الحَيَوَانَاتِ وَتَجْلِسُ عَلَى الْكُرْسِيَ قَرِيبًا مِنَ النَّافِذَةِ. تَقْرَأُ زَيْنَبُ الكِتَابَ بِاهْتِمَامٍ وَتَكْتُبُ المَلْحُوظاتِ فِي دَفْتَرِهَا الصَّغِيرِ القِرَاءَةُ هِوَايَةٌ جَمِيلَةٌ تُغَذِّي العَقْلَ وَتَزِيدُ المَعْرِفَةَ تَرْجِعُ زَيْنَبُ إِلَى الْبَيْتِ سَعِيدَة",
        tr: "Bu, şehirdeki büyük merkez kütüphanesidir. Zeynep faydalı kitaplar okumak için her cumartesi kütüphaneye gider. Kütüphane çok sessizdir ve içinde çok sayıda ve çeşitli kitaplar vardır. Zeynep hayvanlar hakkında küçük bir kitap seçer ve pencereye yakın bir sandalyeye oturur. Zeynep kitabı ilgiyle okur ve küçük defterine notlar alır. Okumak aklı besleyen ve bilgiyi artıran güzel bir hobidir. Zeynep eve mutlu döner.",
        dict: { "هَذِهِ": "bu", "المَكْتَبَةُ": "kütüphane", "المَرْكَزِيَّةُ": "merkez", "الكَبِيرَةُ": "büyük", "فِي": "de/da", "المَدِينَةِ": "şehirde", "تَذْهَبُ": "gider", "زَيْنَبُ": "Zeynep", "إِلَى": "e/a", "كُلَّ": "her", "يَوْمِ": "günü", "سَبْتٍ": "cumartesi", "لِقِرَاءَةِ": "okumak için", "الكُتُبِ": "kitapları", "الْمُفِيدَةِ": "faydalı", "هَادِئَةٌ": "sessizdir", "جِدًا": "çok", "وَفِيهَا": "ve içinde vardır", "كُتُبٌ": "kitaplar", "كَثِيرَةٌ": "çok", "وَمُتَنَوّعَةٌ": "ve çeşitli", "تَخْتَارُ": "seçer", "كِتَابًا": "bir kitap", "صَغِيرًا": "küçük", "عَنِ": "hakkında", "الحَيَوَانَاتِ": "hayvanlar", "وَتَجْلِسُ": "ve oturur", "عَلَى": "üzerinde", "الْكُرْسِيَ": "sandalye", "قَرِيبًا": "yakın", "مِنَ": "den/dan", "النَّافِذَةِ": "pencereye", "تَقْرَأُ": "okur", "بِاهْتِمَامٍ": "ilgiyle", "وَتَكْتُبُ": "ve yazar", "المَلْحُوظاتِ": "notlar", "دَفْتَرِهَا": "defterine", "القِرَاءَةُ": "okumak", "هِوَايَةٌ": "hobi", "جَمِيلَةٌ": "güzel", "تُغَذِّي": "besler", "العَقْلَ": "aklı", "وَتَزِيدُ": "ve artırır", "المَعْرِفَةَ": "bilgiyi", "تَرْجِعُ": "döner", "سَعِيدَة": "mutlu" },
        quiz: { question: "مَتَى تَذْهَبُ زَيْنَبُ إِلَى المَكْتَبَةِ؟ (Zeynep kütüphaneye ne zaman gider?)", options: ["كُلَّ يَوْمِ سَبْتٍ (Her cumartesi)", "كُلَّ يَوْمِ جُمُعَةٍ (Her cuma)", "كُلَّ يَوْمِ أَحَدٍ (Her pazar)", "كُلَّ يَوْمِ اثْنَيْنِ (Her pazartesi)"], correctIndex: 0 }
    }
    /* Not: 100 hikayenin tamamı dosyalar halinde taranarak sisteme taranmıştır */
);